### ISSUE TITLE
About LSTM Layer in GroundHog 

### ISSUE THREAD

**Issue by gaoyuankidult** [lisa-groundhog/GroundHog#23]
Hello 

I have checked the LSTM Layer in GroundHog / groundhog / layers / rec_layers.py. I wonder is this a complete standard LSTM layer(e.g. described in Alex Grave's paper, http://arxiv.org/pdf/1308.0850v5.pdf ) or a prototype for now? 

I didn't see bias term  in # input/output gate update. did I miss it? btw. do you have an example using this layer?

thanks.

btw. I can write a wiki(tutorial) about it, If there is some example.

formulas described in paper:

![gh](https://cloud.githubusercontent.com/assets/1174296/4992781/5b0d7452-69ae-11e4-9ad7-b4f6416ff073.png)

code of LSTM layer:

![hg_code](https://cloud.githubusercontent.com/assets/1174296/4992844/71c1edb2-69af-11e4-916a-92597706bf12.png)

**Comment by infinitezxc** [comment]
Hello @kyunghyuncho 

When I am trying to train a model using LSTM, I run into this error:
‘’‘
ValueError: dimension mismatch in args to gemm (512,2000)x(1000,1000)->(512,1000)
Apply node that caused the error: GpuDot22(GpuReshape{2}.0, W_0_dec_repr_readout)
Inputs types: [CudaNdarrayType(float32, matrix), CudaNdarrayType(float32, matrix)]
Inputs shapes: [(512, 2000), (1000, 1000)]
Inputs strides: [(2000, 1), (1000, 1)]
Inputs values: ['not shown', 'not shown']
’‘’
Do you have any suggestions? Thanks!

**Comment by kyunghyuncho** [comment]
Can you provide your state variables?

**Comment by infinitezxc** [comment]
Thanks for the quick reply :) @kyunghyuncho 

I am using the default states in ```prototype_phrase_lstm_state()```, with the source and target paths modified and adding a '''prototype_phrase_lstm_state''' line at the end of __init__.py.

**Comment by guxd** [comment]
@infinitezxc  Have you solved the LSTM error? I met the error too.
