### ISSUE TITLE
IOError when saving model on disk

### ISSUE THREAD

**Issue by DmitryKey** [lisa-groundhog/GroundHog#24]
Hi,

I'm trying to train a translation model on mac 64 bit using experiments/nmt/train.py

The options:

```
python train.py --proto=prototype_encdec_state --state ru-data.py
```

where ru-data.py is:

```
dict(
  source=["ru-en/binarized.ru.shuf.h5"],
  target="ru-en/binarized_text.en.shuf.h5",
  word_indx="ru-en/vocab.ru.pkl",
  word_indx_trgt="ru-en/vocab.en.pkl",
  indx_word="ru-en/ivocab.ru.pkl",
  indx_word_target="ru-en/ivocab.en.pkl",
  reload=False
)
```

export THEANO_FLAGS=floatX=float32

The IO error happens upon model saving:

``` python
2014-12-09 21:37:31,407: __main__: DEBUG: Load data
2014-12-09 21:37:31,407: __main__: DEBUG: Compile trainer
2014-12-09 21:37:32,011: groundhog.trainer.SGD_adadelta: DEBUG: Constructing grad function
2014-12-09 21:37:32,253: groundhog.trainer.SGD_adadelta: DEBUG: Compiling grad function
2014-12-09 21:38:31,497: groundhog.trainer.SGD_adadelta: DEBUG: took 59.2441170216
2014-12-09 21:38:35,031: __main__: DEBUG: Run training
Validation computed every 500
Saving the model...
Model saved, took 4.50665020943
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "~/projects/machine_translation/rnn/GroundHog/groundhog/datasets/TM_dataset.py", line 175, in run
    target_table = tables.open_file(diter.target_file, 'r', driver=driver)
  File "/Library/Python/2.7/site-packages/tables/file.py", line 318, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/Library/Python/2.7/site-packages/tables/file.py", line 791, in __init__
    self._g_new(filename, mode, **params)
  File "tables/hdf5extension.pyx", line 359, in tables.hdf5extension.File._g_new (tables/hdf5extension.c:3875)
  File "/Library/Python/2.7/site-packages/tables/utils.py", line 157, in check_file_access
    raise IOError("``%s`` does not exist" % (filename,))
IOError: ``r`` does not exist
```

Am I missing something?

**Comment by Lotemp** [comment]
Hello @DmitryKey , I'm struggling with this issue. I keep getting this error:

if i2w[seq[k]] == '<eol>':
KeyError: 2708

with various keys.

The size of the vocabulary is determined by the vocab.pkl files?

Thanks! Lotem

**Comment by DmitryKey** [comment]
hi @Lotemp I would suggest opening a new issue, as this one has been closed. That way your question might be better noticed.

On the size, yes, check the sizes of the pickle files. I will double check soon.

**Comment by DmitryKey** [comment]
@Lotemp when using https://github.com/lisa-groundhog/GroundHog/blob/master/experiments/nmt/preprocess/preprocess.py you can pass -v option for controlling the dictionary size.

**Comment by Lotemp** [comment]
Thanks Dmitry !
I know that GroundHog is not maintained and I'm looking into changing
working with Blocks instead, but I don't wish to throw away all of the
progress I made with GroundHog, so one more question- is it possible to
preform validation with GroundHog? It seems that the iterator for the
validation data is not used at all, and regularization is not used or
implemented?
Thanks in advance for your help
Lotem

2016-11-03 8:02 GMT+02:00 Dmitry Kan notifications@github.com:

**Comment by Lotemp** [comment]
Hi lisa-groundhog/Groun,

I'd like to add you to my professional network on LinkedIn.
- Lotem

Confirm that you know Lotem: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=Osn7XTli&invitationId=6200045383129841664&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eiv2tq6wm%7Egt

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-iv2tq6wm-gt&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHGYDqNJHUkpgAAAVgr80T4dukBUWdCLgK_i7bHCoCIdIqmEY3dyYYBre-EjHwEGlWDBbKLLqKrvwam0DgxkWLkFYNLFckWiiLLr4S-rCiIiCD3tNKqQ5jvle0Ytv6vXMxOQdUWwghj4ABMRjJVX3u7y5wq7lZrtRXXDpZ8_SjSwJ_8PA9Ye2zYphUQNnmGAPct&eid=0-iv2tq6wm-gt

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-iv2tq6wm-gt&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by DmitryKey** [comment]
@Lotemp Blocks sounds like a good plan. For the validation -- I didn't dig into this. The only perf metric I pay attention to is the one outputted by the framework during training:

```
iter 7771 cost 5371.263 grad_norm 1.82e+03 log2_p_word 8.66e+00 log2_p_expl 1.21e+02 step time  3.562 min whole time 15.667 min lr 1.00e+00
iter 7772 cost 6108.257 grad_norm 1.70e+03 log2_p_word 8.75e+00 log2_p_expl 1.38e+02 step time  4.077 min whole time 19.744 min lr 1.00e+00
iter 7773 cost 6365.488 grad_norm 2.10e+03 log2_p_word 8.59e+00 log2_p_expl 1.43e+02 step time  4.266 min whole time 24.011 min lr 1.00e+00
```

**Comment by Lotemp** [comment]
Lotem Peled would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=Osn7XTli&invitationId=6200045383129841664&trk=eml-first_guest_reminder_01-hero-121-accept_text&trkEmail=eml-first_guest_reminder_01-hero-121-accept_text-null-%7Eg6owfx%7Eivar6xko%7E1w

View Lotem Peled&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=Osn7XTli&invitationId=6200045383129841664&trk=eml-first_guest_reminder_01-hero-3-profile_text&trkEmail=eml-first_guest_reminder_01-hero-3-profile_text-null-%7Eg6owfx%7Eivar6xko%7E1w

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-g6owfx-ivar6xko-1w&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=123&m=unsub&ts=HTML&eid=-g6owfx-ivar6xko-1w&loid=AQG6xoR7QnBpcgAAAVhJcOX-XlX65XLPm2sKsk9eQQKtJwK7WYTWPHnpZ-i6opYuT9QKR3JImbKBdszn5zTbgB9b1Y6Ioqj7DGvv7jG3yq3SKT9MHTH5BAmkLilK3sHCoNfV7Xzge09baLEE9jUWx9S5Ih_Sq_slhHqEETpchshwPsb66Lh38QIlJzgUkvwggu9n

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-g6owfx-ivar6xko-1w&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by DmitryKey** [comment]
@Lotemp you might want to remove some of the messages above (produced by LinkedIn).

**Comment by Lotemp** [comment]
Hi ,

Lotem Peled would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=Osn7XTli&invitationId=6200045383129841664&trk=eml-second_guest_reminder_01-hero-120-accept_text&trkEmail=eml-second_guest_reminder_01-hero-120-accept_text-null-%7Eg6owfx%7Eivkhhzgf%7Eyv

View Lotem Peled&#39;s profile: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=Osn7XTli&invitationId=6200045383129841664&trk=eml-second_guest_reminder_01-hero-3-profile_text&trkEmail=eml-second_guest_reminder_01-hero-3-profile_text-null-%7Eg6owfx%7Eivkhhzgf%7Eyv

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-g6owfx-ivkhhzgf-yv&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=122&m=unsub&ts=HTML&eid=-g6owfx-ivkhhzgf-yv&loid=AQG2zijRlObmrQAAAVhslseqY5jk44z5Hyq1_TTYp0dV4NTW2Y56kwjAk1VdvPwaKQki1P7X0MCXsOuikF0x33U7yxqzZjdUfZJO5Q3COTTS2X2AbbTZPIAAPkebdNnQk-FG2RnRm4vxSzSGBKAGReqCb4SF7f0FdriIgeCp5nKtQZudl6boAktZUN-06JN5qLUu

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-g6owfx-ivkhhzgf-yv&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
