### ISSUE TITLE
RAM issue for training large models

### ISSUE THREAD

**Issue by DmitryKey** [lisa-groundhog/GroundHog#27]
Hello!

It is quite affordable to train NMT model for a relatively small parallel corpus, order of 300k sentence pairs.

When I tried to train a 1m+ model, I get memory issues on Linux and very slow iterations (up to an hour) on Mac. Is there some easy win to mitigate this problem on servers with up to 16 GB RAM? Could you share some technical details of models you have trained, including the used hardware?

**Comment by rizar** [comment]
Sort of surprised to here that, because we are simply iterating sequentially through the dataset. We rely on pytables to do all the caching and unloading magic. Does memory usage grow during program execution or is it big from the beginning?

**Comment by DmitryKey** [comment]
On linux with 16 GB RAM the python process always takes a growing amount of RAM until running out (looks like a memory leak).

On mac with 8 GB the process takes all available memory. First attempt to run the training got auto-killed by OS, second and later attempts succeeded, but, as said, take about 1h per iteration (is it expected?)

**Comment by rizar** [comment]
Which iterator class do you use? One from [here](https://github.com/lisa-groundhog/GroundHog/blob/master/groundhog/datasets/TM_dataset.py)?

**Comment by DmitryKey** [comment]
Here is how I call https://github.com/lisa-groundhog/GroundHog/blob/master/experiments/nmt/train.py:

```
python train.py --proto=prototype_encdec_state "prefix='encdec-50_',seqlen=50,sort_k_batches=20" --state ru-data.py
```

in ru-data.py there is no iterator specific settings. One extra param in it is: reload=True

**Comment by rizar** [comment]
Then I guess it is an issue with the `pytables` module we use for loading data [here](https://github.com/lisa-groundhog/GroundHog/blob/master/groundhog/datasets/TM_dataset.py#L162).  I had a feeling that it is not very stable this summer. I am afraid I can not help more. In fact this is not the most important component and I am pretty sure you can replace it by simple reading from a text file.

**Comment by DmitryKey** [comment]
Here is the screenshot of running under Mac:

![screen shot 2015-03-08 at 14 27 08](https://cloud.githubusercontent.com/assets/123553/6545749/52f91094-c59f-11e4-9d48-783f9a56e500.png)

**Comment by DmitryKey** [comment]
thanks @rizar I should take a look, though the code of this project is yet to familiarise with, so I might bug you guys a bit more later.

**Comment by nouiz** [comment]
Update pytables. Old version had memory bug out my memory is right.

**Comment by DmitryKey** [comment]
currently used pytables version is the latest release: 1.3.1 released Mar
26, 2014.

Do you suggest to update to the current master of pytables?

**Comment by nouiz** [comment]
I recall that old release had problems and they got fixed in newer release.
I do not try the development version. If it is easy for you to test, it
could be useful to try.

Just a note, Groundhog will be replaced by blocks:

https://github.com/bartvm/blocks

But currently it do not have all Groundhog functionality. I was told that
some people are working on that. I do not know if you use case is
implemented right now in blocks or not.

@bartvm can you comment on that?

**Comment by rizar** [comment]
Right, @DmitryKey, I would recommend you to switch to Blocks. The only advantage of Groundhog is that it has do-it-all scripts for machine translation with successful hyperparameter and algorithm choices.  There is a [demo script](https://github.com/bartvm/blocks/tree/master/examples/reverse_words) that trains a model capable of reversing words in a text, it should be a good starting point for a machine translation script.

**Comment by DmitryKey** [comment]
@nouiz I might update pytables to the master, that should be easy enough. Will update this thread with my findings.

@rizar sounds like a way to go, thanks for the demo script.

**Comment by DmitryKey** [comment]
Interesting: switching over to RNNSearch from RNN Encoder-Decoder has fixed the RAM issue. Currently the model is training at 5.5 GB RAM with 1-2 min per step. Closing this issue for now. Thanks everybody!

**Comment by rizar** [comment]
Hold on, did you train your model on CPU?

**Comment by DmitryKey** [comment]
@rizar yes. The model is still training.

Actually, regarding the RAM issue: got an out-of-memory again this morning after 30 iterations. I'm hoping this was an irregular glitch.

Current the CPU+RAM graphs:

![selection_177](https://cloud.githubusercontent.com/assets/123553/6665186/202a9b24-cbdf-11e4-9015-77bbe7cf5ac2.png)
