### ISSUE TITLE
Use your own parallel corpus for training and translation

### ISSUE THREAD

**Issue by yapingzhao** [lisa-groundhog/GroundHog#54]
Hi,
I am a beginner (machine translation) and I would like to ask how to use my own parallel corpus for training and translation. Training and translation of the specific orders and operations? Is there a manual?
Thank you very much, hoping to give answers!
Thanks again.

**Comment by nouiz** [comment]
This project isn't supported anymore. Also, the MILA is stopping developing Theano (GroundHog was based on it). So you probably need to find another project. I don't have one to suggest.

**Comment by yapingzhao** [comment]
Okay thank you.
